### ISSUE TITLE
Undefined notes were hit?

### ISSUE THREAD

**Issue by MisterPiBody** [kokolihapihvi/RockSniffer#10]
Hello.
I took the Current_Song addon as base.
Tried to replace information with my one.
Basically I wanted to make it show the amount of notes that were hit, but then i've got this result.
Any tips on what am i doing wrong?
![notes](https://user-images.githubusercontent.com/30563522/62511328-bca3f400-b81b-11e9-8156-2b0e9fb35336.jpg)

**Comment by kokolihapihvi** [comment]
Hey

According to [INoteData](https://github.com/kokolihapihvi/RockSnifferLib/blob/master/RSHelpers/NoteData/INoteData.cs) it should be `readout.TotalNotesHit` (with a capital T)

You can always open the debug addon in a browser and see exactly what the data structure is.

**Comment by MisterPiBody** [comment]
I've tried it, but no luck. It keeps giving me "undefined"

**Comment by kokolihapihvi** [comment]
What version are you using? In 0.3.0 I think the number is under readout.noteData.TotalNotesHit.
You should be able to see it in the debug addon.

**Comment by MisterPiBody** [comment]
0.3.0
Just fixed it. Had to add "var readout2 = data.memoryReadout.noteData;" and read from it
Thanks for help anyways!
