### ISSUE TITLE
Song tuning

### ISSUE THREAD

**Issue by rncollins** [kokolihapihvi/RockSniffer#14]
Request that Rocksniffer report the path-specific Song Tuning in future versions

**Comment by Friedfisch** [comment]
Hm, i guess the data is available but ... what to report, even RS says for low tunings just custom or there is a capo.

**Comment by JustinAiken** [comment]
Based on all the string0/string1...etc data, you can use these as a reference:

- https://github.com/JustinAiken/rsprogress_server/blob/a476c70ecb4304ded00b6044dc59514877d05dc5/lib/arrangement_detailer.rb#L59-L72

- https://github.com/sandiz/rs-manager/blob/b62f1b8cb9ceb4aee3a0c329fec46f5a82af9f76/src/Components/songlistView.js#L33-L52

**Comment by Friedfisch** [comment]
so actually rsman did some grouping/interpretation of tunings. justin also. :D in the end the question still stands if plain or interpreted stuff should be the output - imho plain strings and capo or not and frontend plugin should figure it out.

**Comment by kokolihapihvi** [comment]
Hey, the latest release (v0.3.1) includes per arrangement tuning in the output. The raw values as well as a name generated from them.
