### ISSUE TITLE
Song_Logger doesn't seem to log

### ISSUE THREAD

**Issue by Boernii** [kokolihapihvi/RockSniffer#16]
I enabled addons in the configuration file, however only current song seems to be working not the song_logger. Is there any other setting I should change/alter?

**Comment by kokolihapihvi** [comment]
Hey!
That should be the only setting you need to check for addons to work.

Which version are you using?
Which browser are you using?
Can you check the javascript console (for most browsers press F12) for any errors, as well as the network tab for failed requests?

It should add the current songs title to the web page when you start the song in game.
