### ISSUE TITLE
This program works in the Rocksmith 2014 ? (no remastered)

### ISSUE THREAD

**Issue by vlm110398** [kokolihapihvi/RockSniffer#21]
This program works in the Rocksmith 2014 ? (no remastered)

**Comment by vlm110398** [comment]
In my Rocksmith 2014 the program don't works, I allow all addons and debug it and nothing.
![image](https://user-images.githubusercontent.com/26334595/94356867-bc8f3500-0069-11eb-9bab-1f900d23b4e7.png)

**Comment by kokolihapihvi** [comment]
Hey.

I only support the latest Steam version of the game.
