### ISSUE TITLE
Discord Rich Presence?

### ISSUE THREAD

**Issue by yeguacelestial** [kokolihapihvi/RockSniffer#22]
I downloaded this tool for Discord Rich Presence, but I think I'm doing something wrong. 

I have the latest release, and execute the .exe. But Discord just shows the same thing; Playing Rocksmith for n minutes.

How should this be configured?

Thanks in advance.

**Comment by kokolihapihvi** [comment]
Hey.

Discord rich presence is currently disabled by default, to enable it, open `config/rpc.json` in a text editor like notepad and change `enabled` from `false` to `true`.
