### ISSUE TITLE
Unproperly closed HTTP request crashes the app

### ISSUE THREAD

**Issue by Warths** [kokolihapihvi/RockSniffer#23]
A non-logged error can occur if the distant host of an HTTP request closes the connection before Rocksniffer is expecting it. 

```
Unhandled Exception : System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   à RockSniffer.Addons.AddonServiceListener.GetRequest(Socket s) dans C:\Users\Jeesus\Documents\Visual Studio 2015\Projects\RockSniffer\RockSniffer\Addons\AddonServiceListener.cs:ligne 102
   à RockSniffer.Addons.AddonServiceListener.ServeClient(Socket s) dans C:\Users\Jeesus\Documents\Visual Studio 2015\Projects\RockSniffer\RockSniffer\Addons\AddonServiceListener.cs:ligne 140
   à RockSniffer.Addons.AddonServiceListener.Listen() dans C:\Users\Jeesus\Documents\Visual Studio 2015\Projects\RockSniffer\RockSniffer\Addons\AddonServiceListener.cs:ligne 96
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
```

To reproduce the crash with high chances, i'm running this code into my python console, after installing the `requests` module

```py
import requests

host = "http://127.0.0.1:9938/"

# This will poll RockSniffer as fast as it can, making it likely to raise a SocketException on Rocksniffer's side
while True:
    requests.get(host)
    # Press Ctrl+C to raise a Keyboard Interruption
    # If it doesn't crash the app, try again a few time
```

Fast-polling applications have a quite high chance of not closing their HTTP requests if they do not handle finishing their request before exiting the app, crashing Rocksniffer. This also makes it risky to open the web API to the local network, as any outside source can make it crash, voluntary or not.

Thanks!

**Comment by kokolihapihvi** [comment]
Hey!

For realtime data, I'd like to point out that sniffer internally only [polls every 100ms](https://github.com/kokolihapihvi/RockSnifferLib/blob/0aafa6e760575829f242957f6f4fe6e6c30ea4b0/Sniffing/Sniffer.cs#L174), so having a sleep timer in your code should be fine. If you actually need realtime data, consider reading directly from the games memory, or modify the task delay timer and make a custom build (maybe that could be added as a config option?).

**Comment by Warths** [comment]
100ms is the poll rate i'm actually using in production. I'm still encountering this exception from time to time - quite rare, but annoying enough to be the reason i opened the issue. 

Rocksniffer just crashes sometimes, and i had to wrap it in an auto-restart loop. 

I'm not the only one who have done that to compensate for this bug, as there's a restart loop actionscript in Th0lamin's setup details too, and i've witnessed a few crashes in-stream over the past year, that I think are due to this bug, combined with unloading OBS sources that polls the app.

Polling it at max rate was only for reproduction purpose, of course.

Thanks again for your awesome and inspiring work!
