### ISSUE TITLE
[Merge Request] Adding CustomsForge Sync Feature

### ISSUE THREAD

**Issue by sabihismail** [kokolihapihvi/RockSniffer#29]
Hey, I made changes to your project in another local repo, would you be cool with me making a PR to merge it? It essentially is an additional feature where you can set a config to look for certain artists automatically, as well as thru all your already downloaded artists thru CustomsForge API, and notify you in the client with the direct link to that file. Let me know if that sounds cool, I'll merge it with yours.

**Comment by kokolihapihvi** [comment]
Hey.
I don't recall CustomsForge having an API, and bypassing their site to download songs goes against their rules as far as I know.
Other than that this doesn't sound like it's within the scope of the project.

**Comment by sabihismail** [comment]
Yeah it's a bit of a hack. No worries!
