### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by Centribo** [kokolihapihvi/RockSniffer#3]
Trying to run version 0.1.1 and if Rocksmith 2014 Remastered is running, this is the console output before the whole application crashes:

![image](https://user-images.githubusercontent.com/6460973/38946561-d396226c-4307-11e8-8712-ea85a13602c7.png)

Running Windows 10, 64-Bit

**Comment by kokolihapihvi** [comment]
Hey!

Does the program work if you manage to get it started without crashing?

**Comment by Centribo** [comment]
I'm unable to get the program to do anything other than crash. Using version 0.0.3, it will output:
`Current state: IN_MENUS`
before throwing the same error and crashing. Running either version as administrator also gives the same results.

**Comment by kokolihapihvi** [comment]
The code in question hasn't really changed since the very beginning, I suspect it's something related to windows 10 or your setup...

I don't have a windows 10 machine at hand to do testing with, and I can't replicate the issue on my windows 7 64-bit machine.

I think the best I can do at this point is catch the exception and see if it's just one particular type of handle that's causing the exception, and if other handles in the list would go through.

Would you be able to do some testing on your machine and submit a PR if you find a solution?

**Comment by Friedfisch** [comment]
I played around with that a bit, its uncatchable and happens here: 
`for (long lIndex = 0; lIndex < lHandleCount; lIndex++)
            {
                shHandle = new Win32API.SYSTEM_HANDLE_INFORMATION();
                //Logger.Log("Checking {0}/{1}", lIndex, lHandleCount);
                try
                {
                    //Read struct from pointer and assign SYSTEM_HANDLE_INFORMATION object
                    if (Is64Bits())
                    {
                        shHandle = (Win32API.SYSTEM_HANDLE_INFORMATION)Marshal.PtrToStructure(ipHandle, shHandle.GetType());
                        ipHandle = new IntPtr(ipHandle.ToInt64() + Marshal.SizeOf(shHandle) + 8);
                    }
                    else
                    {
                        shHandle = (Win32API.SYSTEM_HANDLE_INFORMATION)Marshal.PtrToStructure(ipHandle, shHandle.GetType());
                        ipHandle = new IntPtr(ipHandle.ToInt32() + Marshal.SizeOf(shHandle) + 4);
                    }
                }
                catch (Exception e)
                {
                    Logger.Log("UGH"); // we never reach this
                    Logger.Log("Exception: {0} {1} {2}", e, shHandle.ProcessID, shHandle.GrantedAccess);
                }


                //Skip if it belongs to another process
                if (shHandle.ProcessID != process.Id)
                    continue;

                //Add handle to the list
                lstHandles.Add(shHandle);
                Logger.Log("Handles added to {0}[{1}]: {2} {3} {4}", process.ProcessName, process.Id, lstHandles.Count, shHandle.ProcessID, shHandle.GrantedAccess);
            }`
So i guess something is preventing Marshal.PtrToStructure from reading that memory.

**Comment by kokolihapihvi** [comment]
Looking at the stacktrace, looks like the exception is thrown either [here](https://github.com/kokolihapihvi/RockSnifferLib/blob/5e6f9a1827b7465294251a36fa73f05d6d30e397/SysHelpers/FileDetails.cs#L116) or [here](https://github.com/kokolihapihvi/RockSnifferLib/blob/5e6f9a1827b7465294251a36fa73f05d6d30e397/SysHelpers/FileDetails.cs#L175)...

**Comment by Zorglub82** [comment]
Hello!

I have the very same issue and cannot use Rocksniffer anymore :'(
It happened when I changed for a new PC with Windows 10 installed.

**Comment by kokolihapihvi** [comment]
Can you check if the issue still exists on the newest release?
https://github.com/kokolihapihvi/RockSniffer/releases/tag/v0.1.3

**Comment by Zorglub82** [comment]
It works now! Thank you so much!
