### ISSUE TITLE
Executable hash issue

### ISSUE THREAD

**Issue by KielD-01** [kokolihapihvi/RockSniffer#34]
Hey there!

After launching Rocksmith (licensed) and then RoskSniffer, I am getting next issue:

[17.09.2022 15:13:37] RockSniffer is up to date
[17.09.2022 15:13:51] RockSniffer 0.4.0 (64bits)
[17.09.2022 15:13:51] Waiting for rocksmith
[17.09.2022 15:13:52] RockSniffer is up to date
[17.09.2022 15:13:57] Rocksmith found! Sniffing...
[17.09.2022 15:13:58] Rocksmith executable hash: GxT+/TXLpUFys+Cysek8zg==
[17.09.2022 15:13:58] Executable hash does not match expected hash, make sure you have the correct version
[17.09.2022 15:13:58] Press any key to exit

Is there any way to solve this?

OS : Windows 10

**Comment by kokolihapihvi** [comment]
Hey.

The 0.4.0 version only works with the september rocksmith 2014 update, that hash is of the previous version.
Either update rocksmith to the new version, or use a previous version of RockSniffer.

**Comment by KielD-01** [comment]
@kokolihapihvi Okay. Will check this out and get back to You.

**Comment by KielD-01** [comment]
Looks like that issue hasn't been resolved yet for Rocksmith. It's not yet stable for those, who have mods or/adnd CDLC.
So, I'll wait for an update of RS and leave a comment after, if it did worked properly

**Comment by Ryochan7** [comment]
Ubisoft broke it on purpose. Some mods have been updated for the latest RS2014 patch but it is probably still best to run the previous_version beta build and RockSniffer 0.3.4.

https://github.com/kokolihapihvi/RockSniffer/releases/tag/v0.3.4

**Comment by kozaka-tv** [comment]
Yesterday I deleted RS from steam and from the drive directly, and then installad fresh the latest RS. This works with all the updated tools, like Sniffer, RSMods, etc.

This is what solved the problem for me. If you wanna update to the latest and not use the beta anymore, you have to:
- Move your CDLC director to somewhere
- Backup RSMods.ini from RS dir.
- Do a complete delete and install of RS. Delete in Steam, then delete the complete directory of RS directory too.
- Install RS
- Copy back your CDLC-s
- Copy the RSMods.ini to the root of RS
- Add the D3DX9_42.dll to the the root of RS
- Install RSMods 1.2.7.1
- Install Rocksniffer 0.4.0
