### ISSUE TITLE
songDetails is always null

### ISSUE THREAD

**Issue by v-lima95** [kokolihapihvi/RockSniffer#36]
My addons weren't working, then when debbuging I realized that Rocksniffer can't get Song Details.

![image](https://user-images.githubusercontent.com/83465047/191336554-9f3a1f86-93d6-4b7c-a747-f511c62b620e.png)

I tested with official DLCs, CDLCs, base game songs and problem persists.

As it can be seem on the image above, I'm using the version 0.3.4 and the previous version of Rocksmith. That's because I couldn't make RS ASIO newer version work on the current Rocksmith version.

**Comment by kokolihapihvi** [comment]
Hey.

Are you using the disable song previews mod from RSMods?
RockSniffer 0.3.4 is not compatible with that.

**Comment by v-lima95** [comment]
> Hey.
> 
> Are you using the disable song previews mod from RSMods? RockSniffer 0.3.4 is not compatible with that.


that was it! thanks for the help
