### ISSUE TITLE
How can i fix "Executable hash does not match expected hash, make sure you have the correct version"?

### ISSUE THREAD

**Issue by DiezNote** [kokolihapihvi/RockSniffer#37]
(im sorry. eng isnt my native lang, but ill try my best)
Im sorry if it isnt the right place for such questions, but i tried everything that i could do i guess 😅
[Win 10, Steam Rocksmith 2014, RockSniffer 0.3.4]
![image](https://user-images.githubusercontent.com/22731938/193617881-072f7f15-0723-4098-92f6-91504fe37ce2.png)
![image](https://user-images.githubusercontent.com/22731938/193620465-bf92a1cc-2f6f-4ee8-9a6c-35c39e3624f4.png)
Everything worked grate, but one day my Rocksmith didn't want to open, so i reinstalled it. Then i add that dll for custom sonds. Rocksmith started working but Rocksniffer started writing this message. I reinstalled this version, installed new version but nothing helped. 
What should i do to fix this? Thanks!

**Comment by kokolihapihvi** [comment]
Hi.

That hash is for the last months update, RockSniffer 0.4.0 should work with that version.

**Comment by DiezNote** [comment]
yep. Thanks, man! downloaded v0.4.0 and its workig grate! and maybe updating my .net to v6 helped too somehow 😅
