### ISSUE TITLE
No Handles Found error

### ISSUE THREAD

**Issue by QuasarPhil** [kokolihapihvi/RockSniffer#4]
Hey there, haven't managed to get it to work yet, this is my current output:

![nohandles](https://user-images.githubusercontent.com/43919741/46577131-b56a4a80-c9ac-11e8-98b1-008cd47844f8.png)

Any recommendations?

**Comment by kokolihapihvi** [comment]
Hey, this is a known issue with Windows 10 with no known solution at the moment.
