### ISSUE TITLE
Executable Hash Issue

### ISSUE THREAD

**Issue by Arashikaiju** [kokolihapihvi/RockSniffer#44]
To my knowledge, I have the current version of Raocksmith 2014 Remastered, and I'm trying to run Rocksniffer 4.0.1. This is the error message I'm getting, and since everything is (or should be current) I have no idea why. Can anyone help?
![RSHash](https://user-images.githubusercontent.com/130697531/231851525-7a8946d5-5dee-46bc-b904-a5da327857ed.jpg)

**Comment by kozaka-tv** [comment]
Something is wrong with your RS probably. Try to check local files. If does not helps, reinstall. If does not helps, delete completelly (save your CDLCs first!) and install. Should work....I think this is what could fix your problem!

**Comment by Arashikaiju** [comment]
Thanks, a reinstall did it. Dunno what the issue was, but it's working properly now. Strange...
