### ISSUE TITLE
 Album Art

### ISSUE THREAD

**Issue by Drockzoids** [kokolihapihvi/RockSniffer#46]
Where does Rocksniffer store the album art?  One of my songs is Black Lab This Night and the cover is probably not stream friendly, so I wanted to modify it slightly.

**Comment by kokolihapihvi** [comment]
Hi, dlc details are stored in the `cache.sqlite` file, which you can open with any SQLite browser, e.g. [DB Browser for SQLite](https://sqlitebrowser.org/).
It should technically be possible to export the image out of the `album_art` column, modify it, and import the modified version back into the cache.

However, a more permanent solution would be to modify the song file and change it there instead.
