### ISSUE TITLE
Song Logger Black text

### ISSUE THREAD

**Issue by Replicatorz** [kokolihapihvi/RockSniffer#5]
I need it to be white text, how do i change the text color?

**Comment by kokolihapihvi** [comment]
Hi!

You will need to add a style rule in the [style.css](https://github.com/kokolihapihvi/RockSniffer/blob/106ce07602e346d62173948f68bff75aa478b086/addons/song_logger/style.css#L3) file in the song_logger folder.

To change the text color you'd just add a line in the body block `color: white;`.
