### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by talier00t** [kokolihapihvi/RockSniffer#50]
![error](https://github.com/kokolihapihvi/RockSniffer/assets/139094763/6ca813b2-28a8-45f8-a89f-29b08fe4d095)
erisim engellendi means access denied. Can someone help?
this happens whenever i open rocksmith

**Comment by talier00t** [comment]
im trying to use the built in discord rich presence. Can someone help me with that too?

**Comment by kokolihapihvi** [comment]
Hi, try running sniffer as admin.
To enable Discord RPC, you'll need to modify the `config/rpc.json` file with any text editor, and set the `"enabled"` value to `true`.

**Comment by talier00t** [comment]
> Hi, try running sniffer as admin. To enable Discord RPC, you'll need to modify the `config/rpc.json` file with any text editor, and set the `"enabled"` value to `true`.

thanks for the help!
