### ISSUE TITLE
Muse - Psycho, album cover shows up as The Muses- The Muses in discord 

### ISSUE THREAD

**Issue by talier00t** [kokolihapihvi/RockSniffer#52]
Album cover doesnt work right with Muse - Psycho

**Comment by sdasda7777** [comment]
Hi, thanks for reporting, I will look into it as soon as possible. Could you post screenshot of the song metadata from CFSM?

**Comment by sdasda7777** [comment]
I believe the issue is the file has incorrect information. This is what I found:

![image](https://github.com/kokolihapihvi/RockSniffer/assets/17746796/17506af6-3666-4a16-9788-2bb11b52eff7)

If you manually change the Album to "Drones", or ask the creator to change it, I believe it should work.

**Comment by talier00t** [comment]
> I believe the issue is the file has incorrect information. This is what I found:
> 
> ![image](https://private-user-images.githubusercontent.com/17746796/298307582-17506af6-3666-4a16-9788-2bb11b52eff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTU5MjcsIm5iZiI6MTcwNTc5NTYyNywicGF0aCI6Ii8xNzc0Njc5Ni8yOTgzMDc1ODItMTc1MDZhZjYtMzY2Ni00YTE2LTk3ODgtMmJiMTFiNTJlZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAwMDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZWIwNGQxNzliN2FhODJjOGU5MWFlNTMyZjMxNTE2ZmUzNWY1NmE3N2EwNjdkY2I1MmE4MzhjYTljZTI1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FeMmjIwNsvYp32jEGY-oH1Z2gDRxUwLFKJVe0JY54gM)
> 
> If you manually change the Album to "Drones", or ask the creator to change it, I believe it should work.

thanks for the help
