### ISSUE TITLE
Track current arrangement / instrument ? 

### ISSUE THREAD

**Issue by Warths** [kokolihapihvi/RockSniffer#9]
Hey ! Thanks for your work.
Is there any way Rocksniffer can track the current arrangement / instrument (lead, rythm, bass)
If not, could this data be added on the listener ?
Thanks !

**Comment by Friedfisch** [comment]
As far as code looks like it already knows but does not expose it.

**Comment by Warths** [comment]
Where should i change the code to expose as much data as i need ? I'm not a C# dev so the code is quite obscure to me, as well as the compiling process. I'd need to know the arrangement ID currently played (to log scores), but also if the game is paused (to change the stream scene accordingly). 
Thank you !

**Comment by kokolihapihvi** [comment]
Hey

I've just put together a [new release](https://github.com/kokolihapihvi/RockSniffer/releases/tag/v0.3.0) that includes arrangements in the output.
This has previously been discussed in https://github.com/kokolihapihvi/RockSnifferLib/issues/6

You can look at the addons for examples on how to get the current arrangement, as well as how to communicate with obs from an addon, I'm assuming making a html/javascript addon would be the easiest for you to achieve what you want.
See [timeline](https://github.com/kokolihapihvi/RockSniffer/tree/master/addons/timeline) for examples on how to talk to obs (using the obs-websocket plugin)
See [current song v2](https://github.com/kokolihapihvi/RockSniffer/tree/master/addons/current_song_v2) for examples on how to get arrangement details like type and sections.

As for detecting when the game is paused, you can look at the state and song timer to deduce it.

Hope this helps!

**Comment by Warths** [comment]
Thanks, that's fantastic work ! I gave up when i saw on your discord that detecting the arrangement was hard from the memory, but you did it !
Closing the ticket, keep up the good work !
